(() => {
'use strict';
window.addEventListener('error',e=>{console.error('DEAD SECTOR runtime error',e.error||e.message);});
window.addEventListener('unhandledrejection',e=>{console.error('DEAD SECTOR promise rejection',e.reason);});

const canvas = document.getElementById('game'), ctx = canvas.getContext('2d');
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2);
function resize(){const vv=window.visualViewport;W=Math.max(1,Math.round(vv?.width||innerWidth));H=Math.max(1,Math.round(vv?.height||innerHeight));DPR=Math.min(devicePixelRatio||1,2);canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)} addEventListener('resize',resize); resize();
const $=id=>document.getElementById(id);
const UI={menu:$('menu'),how:$('how'),pause:$('pause'),between:$('between'),gameover:$('gameover'),hud:$('hud'),wave:$('waveNum'),score:$('scoreNum'),left:$('zombiesLeft'),hp:$('hpFill'),hpText:$('hpText'),armor:$('armorFill'),armorText:$('armorText'),weapon:$('weaponName'),ammo:$('ammoText'),grenades:$('grenadeText'),interaction:$('interaction'),toast:$('toast'),damage:$('damageVignette'),cross:$('crosshair')};
const TAU=Math.PI*2, rand=(a,b)=>a+Math.random()*(b-a), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y), lerp=(a,b,t)=>a+(b-a)*t;
function circleRect(cx,cy,r,o){let nx=clamp(cx,o.x,o.x+o.w),ny=clamp(cy,o.y,o.y+o.h);return (cx-nx)**2+(cy-ny)**2<r*r}
function resolveCircleRect(e,o){let nx=clamp(e.x,o.x,o.x+o.w),ny=clamp(e.y,o.y,o.y+o.h),dx=e.x-nx,dy=e.y-ny,d=Math.hypot(dx,dy);if(d<e.r&&d>0){let p=e.r-d;e.x+=dx/d*p;e.y+=dy/d*p;return true}if(d===0&&e.x>o.x&&e.x<o.x+o.w&&e.y>o.y&&e.y<o.y+o.h){let l=e.x-o.x,r=o.x+o.w-e.x,t=e.y-o.y,b=o.y+o.h-e.y,m=Math.min(l,r,t,b);if(m===l)e.x=o.x-e.r;if(m===r)e.x=o.x+o.w+e.r;if(m===t)e.y=o.y-e.r;if(m===b)e.y=o.y+o.h+e.r;return true}return false}
function lineRect(x1,y1,x2,y2,o){const steps=Math.ceil(Math.hypot(x2-x1,y2-y1)/12);for(let i=0;i<=steps;i++){let t=i/steps,x=lerp(x1,x2,t),y=lerp(y1,y2,t);if(x>=o.x&&x<=o.x+o.w&&y>=o.y&&y<=o.y+o.h)return true}return false}
const {maps,makeMap}=window.DeadSectorMaps;
const memoryStore={};
function safeGet(key,fallback='{}'){try{const v=localStorage.getItem(key);return v===null?fallback:v}catch(e){return Object.prototype.hasOwnProperty.call(memoryStore,key)?memoryStore[key]:fallback}}
function safeSet(key,value){memoryStore[key]=value;try{localStorage.setItem(key,value)}catch(e){}}
function safeJSON(key){try{return JSON.parse(safeGet(key,'{}'))||{}}catch(e){return {}}}
let selectedMap=0;const saved=safeJSON('deadSectorSave');saved.bestWave=saved.bestWave||1;saved.highScore=saved.highScore||0;saved.unlock=saved.unlock||1;
function save(){safeSet('deadSectorSave',JSON.stringify(saved))}
function renderMapList(){const el=$('mapList');el.innerHTML='';maps.forEach((m,i)=>{const unlocked=saved.unlock>=m.unlock;const b=document.createElement('button');b.className='mapBtn '+(selectedMap===i?'active':'');b.disabled=!unlocked;b.style.opacity=unlocked?1:.48;b.innerHTML=`<div><b>${m.name}</b><div class="stars">${'★'.repeat(m.stars)}${'☆'.repeat(5-m.stars)}</div><div class="mapMeta">${m.desc}</div></div><span class="tag ${unlocked?'':'locked'}">${unlocked?'READY':'WAVE '+m.unlock}</span>`;b.onclick=()=>{if(unlocked){selectedMap=i;renderMapList()}};el.appendChild(b)});$('records').innerHTML=`Best wave: <b>${saved.bestWave}</b><br>High score: <b>${saved.highScore.toLocaleString()}</b><br>Unlocked sectors: <b>${maps.filter(m=>saved.unlock>=m.unlock).length}/${maps.length}</b>`}
renderMapList();
const DSMobile=window.DeadSectorMobile;
const touchMode=DSMobile.touchMode;
DSMobile.initDeviceUI();
const viewportSize=DSMobile.viewportSize,isPortraitTouch=DSMobile.isPortraitTouch;
const syncOrientation=()=>DSMobile.syncOrientation(resize);
addEventListener('resize',syncOrientation,{passive:true});addEventListener('orientationchange',()=>setTimeout(syncOrientation,180),{passive:true});window.visualViewport?.addEventListener('resize',syncOrientation,{passive:true});syncOrientation();let touchMove={x:0,y:0},touchAim={x:1,y:0};
let state='menu',keys={},mouse={x:W/2,y:H/2,down:false,worldX:0,worldY:0},cam={x:0,y:0,shake:0},last=performance.now(),game=null;
const defaultBinds={up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD',reload:'KeyR',grenade:'KeyG',interact:'KeyF',slot1:'Digit1',slot2:'Digit2',slot3:'Digit3',pause:'Escape'};let binds={...defaultBinds,...safeJSON('deadSectorBinds')},rebinding=null;const bindLabels={up:'Move Up',down:'Move Down',left:'Move Left',right:'Move Right',reload:'Reload',grenade:'Throw Grenade',interact:'Interact / Buy / Repair',slot1:'Weapon Slot 1',slot2:'Weapon Slot 2',slot3:'Weapon Slot 3',pause:'Pause'};function prettyKey(code){return code.replace('Key','').replace('Digit','').replace('Arrow','Arrow ').replace('Escape','Esc').replace('Space','Spacebar')}function saveBinds(){safeSet('deadSectorBinds',JSON.stringify(binds))}function renderControls(){const el=$('controlList');el.innerHTML='';for(const [action,label] of Object.entries(bindLabels)){const name=document.createElement('div');name.className='controlName';name.textContent=label;const btn=document.createElement('button');btn.className='bindBtn'+(rebinding===action?' waiting':'');btn.textContent=rebinding===action?'PRESS A KEY':prettyKey(binds[action]);btn.onclick=()=>{rebinding=action;renderControls()};el.append(name,btn)}const n1=document.createElement('div');n1.className='controlName';n1.textContent='Aim';const f1=document.createElement('div');f1.className='fixedBind';f1.textContent='Mouse';const n2=document.createElement('div');n2.className='controlName';n2.textContent='Fire';const f2=document.createElement('div');f2.className='fixedBind';f2.textContent='Left Mouse';el.append(n1,f1,n2,f2)}function showPausePane(which){const controls=which==='controls';$('pauseMainPane').classList.toggle('hidden',controls);$('pauseControlsPane').classList.toggle('hidden',!controls);$('pauseMainTab').classList.toggle('active',!controls);$('pauseControlsTab').classList.toggle('active',controls);if(controls)renderControls();else rebinding=null}
const ensureAudio=window.DeadSectorAudio.ensure;
const sfx=window.DeadSectorAudio.sfx;
const weaponDefs={
 pistol:{name:'M9 Sidearm',damage:28,rate:.26,mag:12,reserve:96,reload:1.15,spread:.035,pellets:1,range:720,sound:'shot',color:'#e9eef5'},
 smg:{name:'VX-9 SMG',damage:17,rate:.085,mag:32,reserve:192,reload:1.45,spread:.07,pellets:1,range:640,sound:'smg',color:'#55d7ff'},
 shotgun:{name:'M12 Breacher',damage:15,rate:.62,mag:8,reserve:56,reload:1.75,spread:.19,pellets:7,range:470,sound:'rifle',color:'#f2c14e'},
 rifle:{name:'AR-47',damage:35,rate:.145,mag:24,reserve:144,reload:1.65,spread:.035,pellets:1,range:860,sound:'rifle',color:'#ff8f66'}
};

function startGame(){ensureAudio();syncOrientation();if(touchMode){try{const fs=document.documentElement.requestFullscreen||document.documentElement.webkitRequestFullscreen;if(typeof fs==='function'){const r=fs.call(document.documentElement);r?.catch?.(()=>{})}}catch(e){}}resize();const map=makeMap(selectedMap);game={map,wave:0,score:0,kills:0,shots:0,hits:0,time:0,enemies:[],bullets:[],particles:[],pickups:[],grenades:[],corpses:[],waveQueue:0,spawnTimer:0,waveActive:false,power:{double:0,rapid:0},player:{x:map.size[0]/2,y:map.size[1]/2,r:18,hp:100,maxHp:100,armor:0,maxArmor:100,speed:230,weapons:[{id:'pistol',ammo:12,reserve:96}],slot:0,grenades:1,fireCd:0,reloading:0,invuln:0,damageMult:1,fireMult:1,moveMult:1,regen:0},};state='playing';document.body.classList.add('game-live');UI.menu.classList.add('hidden');UI.gameover.classList.add('hidden');UI.pause.classList.add('hidden');UI.between.classList.add('hidden');UI.hud.style.display='block';UI.cross.style.display='block';nextWave(true)}
function nextWave(initial=false){game.wave++;game.waveActive=true;game.waveQueue=6+game.wave*3+Math.floor(game.wave**1.22);if(game.wave%5===0)game.waveQueue+=1;game.spawnTimer=.5;toast(`WAVE ${game.wave} — ${game.wave%5===0?'ELITE SIGNAL DETECTED':'HOSTILES INBOUND'}`);updateHUD()}
function enemyStats(type){const w=game.wave,d=game.map.difficulty||1,scale=s=>Math.round(s*d);if(type==='runner')return{hp:scale(48+w*6),speed:(105+w*1.7)*(1+(d-1)*.38),dmg:scale(12),color:'#d96354',r:14,score:Math.round(120*d)};if(type==='brute')return{hp:scale(260+w*24),speed:(52+w*.8)*(1+(d-1)*.28),dmg:scale(24),color:'#8f4d3b',r:25,score:Math.round(450*d)};if(type==='elite')return{hp:scale(950+w*80),speed:(72+w*.7)*(1+(d-1)*.3),dmg:scale(32),color:'#b44bdb',r:31,score:Math.round(1600*d)};return{hp:scale(92+w*10),speed:(70+w*1.1)*(1+(d-1)*.32),dmg:scale(16),color:'#769057',r:18,score:Math.round(100*d)}}
function spawnEnemy(forceElite=false){const s=game.map.spawns[Math.floor(Math.random()*game.map.spawns.length)],r=Math.random();let type=forceElite?'elite':(r<Math.min(.14+game.wave*.008,.3)?'runner':r>.92&&game.wave>3?'brute':'walker');if(game.wave%5===0&&game.waveQueue===1)type='elite';const st=enemyStats(type);game.enemies.push({x:s.x+rand(-30,30),y:s.y+rand(-30,30),r:st.r,type,hp:st.hp,maxHp:st.hp,speed:st.speed,dmg:st.dmg,color:st.color,score:st.score,attackCd:rand(0,.4),hitFlash:0,wander:rand(-1,1)})}
function shoot(){const p=game.player,w=p.weapons[p.slot],d=weaponDefs[w.id];if(p.reloading>0||p.fireCd>0)return;if(w.ammo<=0){reload();return}w.ammo--;game.shots++;p.fireCd=d.rate/(p.fireMult*(game.power.rapid>0?1.55:1));const a=Math.atan2(mouse.worldY-p.y,mouse.worldX-p.x);for(let k=0;k<d.pellets;k++){const aa=a+rand(-d.spread,d.spread),range=d.range*rand(.88,1.02);let ex=p.x+Math.cos(aa)*range,ey=p.y+Math.sin(aa)*range;for(const o of game.map.obs)if(lineRect(p.x,p.y,ex,ey,o)){const steps=Math.ceil(range/8);for(let i=1;i<=steps;i++){let t=i/steps,x=lerp(p.x,ex,t),y=lerp(p.y,ey,t);if(x>=o.x&&x<=o.x+o.w&&y>=o.y&&y<=o.y+o.h){ex=x;ey=y;break}}break}
 let best=null,bestD=Infinity;for(const e of game.enemies){let vx=ex-p.x,vy=ey-p.y,wx=e.x-p.x,wy=e.y-p.y,c1=vx*wx+vy*wy,c2=vx*vx+vy*vy,t=clamp(c1/c2,0,1),px=p.x+vx*t,py=p.y+vy*t,dd=Math.hypot(e.x-px,e.y-py);if(dd<e.r+4){let along=Math.hypot(px-p.x,py-p.y);if(along<bestD){best=e;bestD=along;ex=px;ey=py}}}if(best){const mult=(game.power.double>0?2:1)*p.damageMult;best.hp-=d.damage*mult;best.hitFlash=.09;game.hits++;burst(ex,ey,d.color,4,90);if(best.hp<=0)killEnemy(best)}game.bullets.push({x1:p.x,y1:p.y,x2:ex,y2:ey,life:.055,color:d.color});}
 burst(p.x+Math.cos(a)*22,p.y+Math.sin(a)*22,'#ffdca8',3,70);cam.shake=Math.max(cam.shake,d.pellets>1?4:2);sfx(d.sound,.055);updateHUD()}
function reload(){const p=game.player,w=p.weapons[p.slot],d=weaponDefs[w.id];if(p.reloading>0||w.ammo>=d.mag||w.reserve<=0)return;p.reloading=d.reload;sfx('reload',.035);toast('RELOADING')}
function finishReload(){const p=game.player,w=p.weapons[p.slot],d=weaponDefs[w.id],need=d.mag-w.ammo,take=Math.min(need,w.reserve);w.ammo+=take;w.reserve-=take;updateHUD()}
function killEnemy(e){const i=game.enemies.indexOf(e);if(i<0)return;game.enemies.splice(i,1);game.score+=Math.round(e.score*(game.power.double>0?2:1));game.kills++;game.corpses.push({x:e.x,y:e.y,r:e.r,a:Math.random()*TAU,life:9,color:e.color});if(game.corpses.length>35)game.corpses.shift();burst(e.x,e.y,e.color,12,150);if(Math.random()<.04)dropHealing(e.x,e.y);else if(Math.random()<.19)dropPickup(e.x,e.y);updateHUD()}
function dropHealing(x,y){game.pickups.push({x,y,r:14,type:'heal',life:14,bob:Math.random()*TAU})}
function dropPickup(x,y){const r=Math.random();let type=r<.27?'ammo':r<.49?'armor':r<.67?'grenade':r<.84?'double':'rapid';game.pickups.push({x,y,r:13,type,life:14,bob:Math.random()*TAU})}
function pickup(pu){const p=game.player;if(pu.type==='ammo'){for(const w of p.weapons){const d=weaponDefs[w.id];w.reserve=Math.min(w.reserve+Math.ceil(d.mag*1.8),d.reserve*2)}toast('AMMO RESTOCKED')}if(pu.type==='armor'){p.armor=Math.min(p.maxArmor,p.armor+45);toast('+45 ARMOR')}if(pu.type==='grenade'){p.grenades=Math.min(5,p.grenades+1);toast('+1 GRENADE')}if(pu.type==='heal'){const amount=Math.min(40,p.maxHp-p.hp);p.hp=Math.min(p.maxHp,p.hp+40);burst(p.x,p.y,'#59d98e',14,130);toast(amount>0?'+'+Math.ceil(amount)+' HEALTH':'HEALTH FULL')}if(pu.type==='double'){game.power.double=12;toast('DOUBLE POINTS — 12s')}if(pu.type==='rapid'){game.power.rapid=12;toast('OVERDRIVE — 12s')}sfx('pickup',.05);game.pickups.splice(game.pickups.indexOf(pu),1);updateHUD()}
function throwGrenade(){const p=game.player;if(p.grenades<=0)return;p.grenades--;const a=Math.atan2(mouse.worldY-p.y,mouse.worldX-p.x);game.grenades.push({x:p.x,y:p.y,vx:Math.cos(a)*520,vy:Math.sin(a)*520,t:1.15,r:7});updateHUD();toast('GRENADE OUT')}
function explode(g){sfx('boom',.16);cam.shake=12;burst(g.x,g.y,'#ffb347',36,360);for(const e of [...game.enemies]){let d=Math.hypot(e.x-g.x,e.y-g.y);if(d<185){e.hp-=Math.max(0,260*(1-d/230))*game.player.damageMult;if(e.hp<=0)killEnemy(e)}}}
function burst(x,y,color,n=8,speed=100){for(let i=0;i<n;i++){let a=Math.random()*TAU,s=rand(speed*.3,speed);game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.18,.55),max:.55,size:rand(2,5),color})}}
function toast(txt){const d=document.createElement('div');d.className='toast';d.textContent=txt;UI.toast.appendChild(d);setTimeout(()=>d.remove(),2300)}
function damagePlayer(amount){const p=game.player;if(p.invuln>0)return;p.invuln=.2;let left=amount;if(p.armor>0){let absorb=Math.min(p.armor,left*.65);p.armor-=absorb;left-=absorb}p.hp-=left;UI.damage.style.opacity=.75;setTimeout(()=>UI.damage.style.opacity=0,120);cam.shake=7;sfx('hurt',.08);if(p.hp<=0)endGame();updateHUD()}
function interact(){const p=game.player;let best=null,bd=72,type='';for(const s of game.map.shops){let d=Math.hypot(p.x-s.x,p.y-s.y);if(d<bd){best=s;bd=d;type='shop'}}for(const b of game.map.barr){let cx=b.x+b.w/2,cy=b.y+b.h/2,d=Math.hypot(p.x-cx,p.y-cy);if(d<bd&&b.hp>0&&b.hp<b.maxHp){best=b;bd=d;type='barr'}}if(type==='shop'){const has=p.weapons.some(w=>w.id===best.weapon);if(has){const w=p.weapons.find(w=>w.id===best.weapon),def=weaponDefs[w.id],cost=450;if(game.score>=cost){game.score-=cost;w.reserve=Math.min(w.reserve+def.mag*2,def.reserve*2);toast('AMMO PURCHASED');sfx('buy',.05)}else toast('NOT ENOUGH SCORE')}else if(game.score>=best.cost){game.score-=best.cost;p.weapons.push({id:best.weapon,ammo:weaponDefs[best.weapon].mag,reserve:weaponDefs[best.weapon].reserve});p.slot=p.weapons.length-1;toast(weaponDefs[best.weapon].name+' ACQUIRED');sfx('buy',.07)}else toast('NOT ENOUGH SCORE')}
 if(type==='barr'){const cost=250;if(game.score>=cost){game.score-=cost;best.hp=Math.min(best.maxHp,best.hp+160);toast('BARRICADE REPAIRED');sfx('buy',.05)}else toast('NOT ENOUGH SCORE')}updateHUD()}
function updateInteraction(){const p=game.player;let txt='',bd=80;for(const s of game.map.shops){let d=dist(p,s);if(d<bd){const has=p.weapons.some(w=>w.id===s.weapon);txt=`${touchMode?'[USE]':'['+prettyKey(binds.interact)+']'} ${has?'BUY AMMO — 450':'BUY '+weaponDefs[s.weapon].name+' — '+s.cost}`;bd=d}}for(const b of game.map.barr){let d=Math.hypot(p.x-(b.x+b.w/2),p.y-(b.y+b.h/2));if(d<bd&&b.hp>0&&b.hp<b.maxHp){txt=`${touchMode?'[USE]':'['+prettyKey(binds.interact)+']'} REPAIR BARRICADE — 250`;bd=d}}UI.interaction.textContent=txt;UI.interaction.style.opacity=txt?1:0}
function chooseUpgrades(){const pool=[
 {t:'Stopping Power',d:'+20% weapon damage.',f:()=>game.player.damageMult*=1.2},
 {t:'Fleet Foot',d:'+12% movement speed.',f:()=>game.player.moveMult*=1.12},
 {t:'Fast Hands',d:'+16% fire rate.',f:()=>game.player.fireMult*=1.16},
 {t:'Juggernaut',d:'+25 max health and heal 25.',f:()=>{game.player.maxHp+=25;game.player.hp=Math.min(game.player.maxHp,game.player.hp+25)}},
 {t:'Armor Plate',d:'+30 max armor and refill 45.',f:()=>{game.player.maxArmor+=30;game.player.armor=Math.min(game.player.maxArmor,game.player.armor+45)}},
 {t:'Scavenger',d:'Gain 2 grenades and refill weapon reserves.',f:()=>{game.player.grenades=Math.min(5,game.player.grenades+2);for(const w of game.player.weapons){const d=weaponDefs[w.id];w.reserve=Math.min(d.reserve*2,w.reserve+d.mag*2)}}},
 {t:'Demolitions',d:'Gain 2 grenades.',f:()=>game.player.grenades=Math.min(5,game.player.grenades+2)}
 ].sort(()=>Math.random()-.5).slice(0,3);const grid=$('upgradeGrid');grid.innerHTML='';pool.forEach(u=>{const d=document.createElement('div');d.className='upgrade';d.innerHTML=`<h4>${u.t}</h4><p>${u.d}</p><button>SELECT</button>`;d.querySelector('button').onclick=()=>{u.f();UI.between.classList.add('hidden');state='playing';document.body.classList.add('game-live');nextWave();updateHUD()};grid.appendChild(d)});state='between';document.body.classList.remove('game-live');UI.between.classList.remove('hidden')}
function endGame(){state='gameover';document.body.classList.remove('game-live');UI.hud.style.display='none';UI.cross.style.display='none';saved.bestWave=Math.max(saved.bestWave,game.wave);saved.highScore=Math.max(saved.highScore,game.score);if(game.wave>=8)saved.unlock=Math.max(saved.unlock,8);if(game.wave>=15)saved.unlock=Math.max(saved.unlock,15);if(game.wave>=22)saved.unlock=Math.max(saved.unlock,22);if(game.wave>=30)saved.unlock=Math.max(saved.unlock,30);save();renderMapList();$('endStats').innerHTML=`<div class="stat"><b>${game.wave}</b><span>Wave</span></div><div class="stat"><b>${game.score.toLocaleString()}</b><span>Score</span></div><div class="stat"><b>${game.kills}</b><span>Kills</span></div><div class="stat"><b>${game.shots?Math.round(game.hits/game.shots*100):0}%</b><span>Accuracy</span></div>`;UI.gameover.classList.remove('hidden')}
function updateHUD(){if(!game)return;const p=game.player,w=p.weapons[p.slot],d=weaponDefs[w.id];UI.wave.textContent=game.wave;UI.score.textContent=Math.floor(game.score).toLocaleString();UI.left.textContent=`${game.enemies.length+game.waveQueue} hostiles`;UI.hp.style.width=clamp(p.hp/p.maxHp*100,0,100)+'%';UI.hpText.textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;UI.armor.style.width=clamp(p.armor/p.maxArmor*100,0,100)+'%';UI.armorText.textContent=`${Math.ceil(p.armor)} / ${p.maxArmor}`;UI.weapon.textContent=d.name+(p.reloading>0?' · RELOADING':'');UI.ammo.innerHTML=`${w.ammo} <span>/ ${w.reserve}</span>`;UI.grenades.textContent=`Grenades: ${p.grenades}${game.power.double>0?' · 2X '+game.power.double.toFixed(0)+'s':''}${game.power.rapid>0?' · OVERDRIVE '+game.power.rapid.toFixed(0)+'s':''}`}
function update(dt){if(state!=='playing'||!game)return;const p=game.player,m=game.map;game.time+=dt;p.fireCd=Math.max(0,p.fireCd-dt);p.invuln=Math.max(0,p.invuln-dt);if(p.reloading>0){p.reloading-=dt;if(p.reloading<=0)finishReload()}if(game.power.double>0)game.power.double=Math.max(0,game.power.double-dt);if(game.power.rapid>0)game.power.rapid=Math.max(0,game.power.rapid-dt);if(p.regen>0&&p.hp>0&&p.hp<p.maxHp)p.hp=Math.min(p.maxHp,p.hp+p.regen*dt);
 let dx=touchMode?touchMove.x:(keys[binds.right]?1:0)-(keys[binds.left]?1:0),dy=touchMode?touchMove.y:(keys[binds.down]?1:0)-(keys[binds.up]?1:0),len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;let sp=p.speed*p.moveMult;p.x+=dx*sp*dt;for(const o of m.obs)resolveCircleRect(p,o);for(const b of m.barr)if(b.hp>0)resolveCircleRect(p,b);p.y+=dy*sp*dt;for(const o of m.obs)resolveCircleRect(p,o);for(const b of m.barr)if(b.hp>0)resolveCircleRect(p,b);p.x=clamp(p.x,p.r,m.size[0]-p.r);p.y=clamp(p.y,p.r,m.size[1]-p.r);
 if(touchMode){mouse.worldX=p.x+touchAim.x*500;mouse.worldY=p.y+touchAim.y*500} if(mouse.down)shoot();
 if(game.waveActive&&game.waveQueue>0){game.spawnTimer-=dt;if(game.spawnTimer<=0){spawnEnemy();game.waveQueue--;game.spawnTimer=Math.max(.18,.72-game.wave*.025)*rand(.7,1.2)}}
 for(const e of game.enemies){e.attackCd-=dt;e.hitFlash=Math.max(0,e.hitFlash-dt);let ax=p.x-e.x,ay=p.y-e.y,d=Math.hypot(ax,ay)||1,blocked=false,targetBarr=null;for(const b of m.barr)if(b.hp>0&&lineRect(e.x,e.y,p.x,p.y,b)){targetBarr=b;blocked=true;break}if(blocked&&targetBarr){let tx=targetBarr.x+targetBarr.w/2,ty=targetBarr.y+targetBarr.h/2,dd=Math.hypot(tx-e.x,ty-e.y)||1;e.x+=(tx-e.x)/dd*e.speed*dt;e.y+=(ty-e.y)/dd*e.speed*dt;if(circleRect(e.x,e.y,e.r+5,targetBarr)&&e.attackCd<=0){targetBarr.hp-=e.dmg*1.3;e.attackCd=.65;if(targetBarr.hp<=0){targetBarr.hp=0;burst(tx,ty,'#9b7a5b',20,180);toast('BARRICADE DESTROYED')}}}else{e.x+=ax/d*e.speed*dt;e.y+=ay/d*e.speed*dt}for(const o of m.obs)resolveCircleRect(e,o);for(const b of m.barr)if(b.hp>0)resolveCircleRect(e,b);if(Math.hypot(e.x-p.x,e.y-p.y)<e.r+p.r+3&&e.attackCd<=0){damagePlayer(e.dmg);e.attackCd=e.type==='runner'?.65:e.type==='elite'?.55:.82}}
 for(let i=game.pickups.length-1;i>=0;i--){let pu=game.pickups[i];pu.life-=dt;pu.bob+=dt*3;if(pu.life<=0)game.pickups.splice(i,1);else if(Math.hypot(pu.x-p.x,pu.y-p.y)<p.r+pu.r+8)pickup(pu)}
 for(let i=game.grenades.length-1;i>=0;i--){let g=game.grenades[i];g.t-=dt;g.x+=g.vx*dt;g.y+=g.vy*dt;g.vx*=Math.pow(.08,dt);g.vy*=Math.pow(.08,dt);for(const o of m.obs)if(circleRect(g.x,g.y,g.r,o)){g.vx*=-.35;g.vy*=-.35}if(g.t<=0){explode(g);game.grenades.splice(i,1)}}
 for(let i=game.particles.length-1;i>=0;i--){let q=game.particles[i];q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=Math.pow(.1,dt);q.vy*=Math.pow(.1,dt);if(q.life<=0)game.particles.splice(i,1)}for(const b of game.bullets)b.life-=dt;game.bullets=game.bullets.filter(b=>b.life>0);for(const c of game.corpses)c.life-=dt;game.corpses=game.corpses.filter(c=>c.life>0);
 if(game.waveActive&&game.waveQueue===0&&game.enemies.length===0){game.waveActive=false;setTimeout(()=>{if(state==='playing')chooseUpgrades()},600)}
 cam.x=lerp(cam.x,p.x-W/2,.13);cam.y=lerp(cam.y,p.y-H/2,.13);cam.x=clamp(cam.x,0,Math.max(0,m.size[0]-W));cam.y=clamp(cam.y,0,Math.max(0,m.size[1]-H));cam.shake=Math.max(0,cam.shake-20*dt);if(!touchMode){mouse.worldX=mouse.x+cam.x;mouse.worldY=mouse.y+cam.y}updateInteraction();updateHUD()}
function draw(){ctx.clearRect(0,0,W,H);if(!game){drawMenuBG();return}const m=game.map,sh=cam.shake?rand(-cam.shake,cam.shake):0,sv=cam.shake?rand(-cam.shake,cam.shake):0;ctx.save();ctx.translate(-cam.x+sh,-cam.y+sv);ctx.fillStyle=m.floor;ctx.fillRect(0,0,m.size[0],m.size[1]);drawGrid(m);
 for(const c of game.corpses){ctx.save();ctx.globalAlpha=clamp(c.life/2,0,.35);ctx.translate(c.x,c.y);ctx.rotate(c.a);ctx.fillStyle=c.color;ctx.beginPath();ctx.ellipse(0,0,c.r*1.2,c.r*.65,0,0,TAU);ctx.fill();ctx.restore()}
 for(const o of m.obs)drawObstacle(o);for(const b of m.barr)drawBarr(b);for(const s of m.shops)drawShop(s);for(const pu of game.pickups)drawPickup(pu);for(const g of game.grenades){ctx.fillStyle='#25303a';ctx.beginPath();ctx.arc(g.x,g.y,g.r,0,TAU);ctx.fill();ctx.strokeStyle='#f2c14e';ctx.stroke()}
 for(const e of game.enemies)drawEnemy(e);drawPlayer(game.player);for(const b of game.bullets){ctx.globalAlpha=clamp(b.life/.055,0,1);ctx.strokeStyle=b.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x1,b.y1);ctx.lineTo(b.x2,b.y2);ctx.stroke();ctx.globalAlpha=1}for(const q of game.particles){ctx.globalAlpha=clamp(q.life/q.max,0,1);ctx.fillStyle=q.color;ctx.fillRect(q.x-q.size/2,q.y-q.size/2,q.size,q.size);ctx.globalAlpha=1}ctx.restore();drawMinimap()}
function drawGrid(m){ctx.strokeStyle='rgba(255,255,255,.025)';ctx.lineWidth=1;for(let x=0;x<m.size[0];x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,m.size[1]);ctx.stroke()}for(let y=0;y<m.size[1];y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(m.size[0],y);ctx.stroke()}}
function drawObstacle(o){ctx.fillStyle=o.type==='building'?'#252b2e':o.type==='wall'?'#242a31':o.type==='lab'?'#2b242b':'#2c2924';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=3;ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.fillStyle='rgba(255,255,255,.035)';for(let x=o.x+16;x<o.x+o.w-8;x+=34)ctx.fillRect(x,o.y+14,18,4)}
function drawBarr(b){ctx.fillStyle=b.hp>0?'#654b35':'#342c27';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle='#aa8056';ctx.strokeRect(b.x,b.y,b.w,b.h);if(b.hp>0&&b.hp<b.maxHp){ctx.fillStyle='#1a1d20';ctx.fillRect(b.x,b.y-8,b.w,4);ctx.fillStyle='#59d98e';ctx.fillRect(b.x,b.y-8,b.w*(b.hp/b.maxHp),4)}}
function drawShop(s){ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle='rgba(85,215,255,.13)';ctx.beginPath();ctx.arc(0,0,34,0,TAU);ctx.fill();ctx.strokeStyle='#55d7ff';ctx.lineWidth=2;ctx.strokeRect(-18,-12,36,24);ctx.fillStyle='#d9f5ff';ctx.font='700 10px system-ui';ctx.textAlign='center';ctx.fillText(weaponDefs[s.weapon].name,0,-42);ctx.restore()}
function drawPickup(pu){const colors={ammo:'#f2c14e',armor:'#55a8ff',grenade:'#ff765e',heal:'#59d98e',double:'#f2c14e',rapid:'#b16cff'},y=pu.y+Math.sin(pu.bob)*4;ctx.save();ctx.translate(pu.x,y);ctx.shadowBlur=16;ctx.shadowColor=colors[pu.type];ctx.fillStyle=colors[pu.type];ctx.beginPath();ctx.arc(0,0,pu.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#0a0d10';ctx.font='900 9px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText({ammo:'AM',armor:'AR',grenade:'G',heal:'+',double:'2X',rapid:'>>'}[pu.type],0,1);ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);const a=Math.atan2(game.player.y-e.y,game.player.x-e.x);ctx.rotate(a);ctx.fillStyle=e.hitFlash>0?'#ffffff':e.color;ctx.beginPath();ctx.arc(0,0,e.r,0,TAU);ctx.fill();ctx.fillStyle='rgba(0,0,0,.24)';ctx.fillRect(-e.r*.6,-e.r*.35,e.r*1.2,e.r*.7);ctx.fillStyle='#ffefb0';ctx.fillRect(e.r*.25,-e.r*.38,3,3);ctx.fillRect(e.r*.25,e.r*.25,3,3);ctx.restore();if(e.type==='brute'||e.type==='elite'){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(e.x-e.r,e.y-e.r-11,e.r*2,5);ctx.fillStyle=e.type==='elite'?'#d56cff':'#d96354';ctx.fillRect(e.x-e.r,e.y-e.r-11,e.r*2*(e.hp/e.maxHp),5)}}
function drawPlayer(p){const a=Math.atan2(mouse.worldY-p.y,mouse.worldX-p.x);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.fillStyle='#dbe6ef';ctx.beginPath();ctx.arc(0,0,p.r,0,TAU);ctx.fill();ctx.fillStyle='#303a45';ctx.fillRect(6,-5,25,10);ctx.fillStyle='#10161b';ctx.beginPath();ctx.arc(-5,-5,3,0,TAU);ctx.arc(-5,5,3,0,TAU);ctx.fill();ctx.restore()}
function drawMinimap(){if(state!=='playing')return;const m=game.map,mw=150,mh=100,x=W-mw-18,y=90,sx=mw/m.size[0],sy=mh/m.size[1];ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(x,y,mw,mh);ctx.strokeStyle='rgba(255,255,255,.12)';ctx.strokeRect(x,y,mw,mh);ctx.fillStyle='#8b949f';for(const o of m.obs)ctx.fillRect(x+o.x*sx,y+o.y*sy,o.w*sx,o.h*sy);ctx.fillStyle='#ff6257';for(const e of game.enemies)ctx.fillRect(x+e.x*sx-1,y+e.y*sy-1,2,2);ctx.fillStyle='#55d7ff';ctx.beginPath();ctx.arc(x+game.player.x*sx,y+game.player.y*sy,3,0,TAU);ctx.fill()}
function drawMenuBG(){const t=performance.now()/1000;ctx.fillStyle='#07090c';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.025)';for(let x=((t*12)%70)-70;x<W;x+=70){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+180,H);ctx.stroke()}ctx.fillStyle='rgba(255,75,62,.08)';ctx.beginPath();ctx.arc(W*.72,H*.4,180+Math.sin(t)*12,0,TAU);ctx.fill()}
function loop(now){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('keydown',e=>{if(rebinding){e.preventDefault();const oldAction=Object.keys(binds).find(a=>binds[a]===e.code&&a!==rebinding);if(oldAction)binds[oldAction]=binds[rebinding];binds[rebinding]=e.code;rebinding=null;saveBinds();renderControls();return}keys[e.code]=true;if(e.code===binds.pause){e.preventDefault();if(state==='playing'){state='paused';document.body.classList.remove('game-live');UI.pause.classList.remove('hidden');showPausePane('main')}else if(state==='paused'){state='playing';document.body.classList.add('game-live');UI.pause.classList.add('hidden');rebinding=null}return}if(state!=='playing')return;if(e.code===binds.reload)reload();if(e.code===binds.grenade)throwGrenade();if(e.code===binds.interact)interact();const slots=[binds.slot1,binds.slot2,binds.slot3];const i=slots.indexOf(e.code);if(i>=0&&game.player.weapons[i]){game.player.slot=i;game.player.reloading=0;updateHUD()}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;UI.cross.style.left=e.clientX+'px';UI.cross.style.top=e.clientY+'px'});addEventListener('mousedown',e=>{if(e.button===0){mouse.down=true;ensureAudio()}});addEventListener('mouseup',e=>{if(e.button===0)mouse.down=false});addEventListener('contextmenu',e=>e.preventDefault());
DSMobile.installBrowserGuards();

const setupStick=DSMobile.setupStick;
if(touchMode){setupStick('moveStick',(x,y)=>{touchMove.x=x;touchMove.y=y},()=>{touchMove.x=touchMove.y=0});setupStick('aimStick',(x,y)=>{const l=Math.hypot(x,y);if(l>.12){touchAim.x=x/l;touchAim.y=y/l;mouse.down=true;ensureAudio()}},()=>mouse.down=false);const tap=(id,fn)=>$(id).addEventListener('touchstart',e=>{e.preventDefault();ensureAudio();if(state==='playing')fn()},{passive:false});tap('touchReload',reload);tap('touchGrenade',throwGrenade);tap('touchInteract',interact);tap('touchWeapon',()=>{if(!game)return;const p=game.player;p.slot=(p.slot+1)%p.weapons.length;p.reloading=0;updateHUD()});$('mobilePauseBtn').addEventListener('touchstart',e=>{e.preventDefault();if(state==='playing'){state='paused';document.body.classList.remove('game-live');mouse.down=false;touchMove.x=touchMove.y=0;UI.pause.classList.remove('hidden');showPausePane('main')}},{passive:false})}

{const startBtn=$('startBtn');let startLocked=false;
const doStart=e=>{if(e){try{e.preventDefault()}catch(_){}try{e.stopPropagation()}catch(_){}}if(startLocked)return false;startLocked=true;try{startGame();setTimeout(syncOrientation,100)}catch(err){console.error('DEAD SECTOR start error',err);alert('Game failed to start: '+(err&&err.message?err.message:String(err)));}finally{setTimeout(()=>startLocked=false,250)}return false};
window.DeadSectorStart=doStart;
startBtn.addEventListener('touchstart',e=>{if(touchMode)doStart(e)},{passive:false});
startBtn.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')doStart(e)});
}$('howBtn').onclick=()=>{UI.menu.classList.add('hidden');UI.how.classList.remove('hidden')};$('backBtn').onclick=()=>{UI.how.classList.add('hidden');UI.menu.classList.remove('hidden')};$('resumeBtn').onclick=()=>{state='playing';document.body.classList.add('game-live');UI.pause.classList.add('hidden');rebinding=null};$('restartBtn').onclick=()=>{UI.pause.classList.add('hidden');rebinding=null;startGame()};$('quitBtn').onclick=()=>{state='menu';document.body.classList.remove('game-live');game=null;rebinding=null;UI.pause.classList.add('hidden');UI.hud.style.display='none';UI.cross.style.display='none';UI.menu.classList.remove('hidden')};$('pauseMainTab').onclick=()=>showPausePane('main');$('pauseControlsTab').onclick=()=>showPausePane('controls');$('controlsBackBtn').onclick=()=>showPausePane('main');$('resetControlsBtn').onclick=()=>{binds={...defaultBinds};saveBinds();rebinding=null;renderControls();toast('CONTROLS RESET')};$('againBtn').onclick=startGame;$('menuBtn').onclick=()=>{state='menu';document.body.classList.remove('game-live');game=null;UI.gameover.classList.add('hidden');UI.menu.classList.remove('hidden')};
})();
