(() => {
'use strict';
fetch('game.js?v=pc3',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Could not load game core');return r.text()}).then(src=>{
  src=src.replace("saved.unlock=saved.unlock||1;",`saved.unlock=saved.unlock||1;if(saved.unlock>5){saved.unlock=saved.unlock>=30?5:saved.unlock>=22?4:saved.unlock>=15?3:saved.unlock>=8?2:1;save();}`);
  src=src.replace(/function renderMapList\(\)\{.*?\}\nrenderMapList\(\);/s,`function renderMapList(){const el=$('mapList');el.innerHTML='';maps.forEach((m,i)=>{const unlocked=saved.unlock>=m.unlock;const b=document.createElement('button');b.className='mapBtn '+(selectedMap===i?'active ':'')+(unlocked?'':'lockedLevel');b.disabled=!unlocked;b.style.opacity=unlocked?1:.28;if(!unlocked)b.dataset.lockhint='Complete Level '+i+' to unlock';b.innerHTML=\`<div><div class="mapLevel">LEVEL \${i+1}</div><div class="mapSite">\${m.name}</div><div class="stars">\${'★'.repeat(m.stars)}</div><div class="mapMeta">\${m.desc}</div></div>\`;b.onclick=()=>{if(unlocked){selectedMap=i;renderMapList()}};el.appendChild(b)});$('records').innerHTML=\`Best wave: <b>\${saved.bestWave}</b><br>High score: <b>\${saved.highScore.toLocaleString()}</b><br>Unlocked levels: <b>\${Math.min(saved.unlock,maps.length)}/\${maps.length}</b>\`}renderMapList();`);
  src=src.replace("grenades:$('grenadeText'),","grenades:null,");
  src=src.replace("grenade:'KeyG',","");src=src.replace("grenade:'Throw Grenade',","");src=src.replace("if(e.code===binds.grenade)throwGrenade();","");src=src.replace("tap('touchGrenade',throwGrenade);","");src=src.replace(/UI\.grenades\.textContent=`Grenades: \$\{p\.grenades\}.*?`/s,"void 0");
  src=src.replace("${'★'.repeat(m.stars)}${'☆'.repeat(5-m.stars)}","${'★'.repeat(m.stars)}");src=src.replace("UI.ammo.innerHTML=`${w.ammo} <span>/ ${w.reserve}</span>`","UI.ammo.textContent=String(w.ammo)");src=src.replace("if(p.reloading>0||w.ammo>=d.mag||w.reserve<=0)return;p.reloading=d.reload","if(p.reloading>0||w.ammo>=d.mag)return;p.reloading=d.reload");src=src.replace("const p=game.player,w=p.weapons[p.slot],d=weaponDefs[w.id],need=d.mag-w.ammo,take=Math.min(need,w.reserve);w.ammo+=take;w.reserve-=take;updateHUD()","const p=game.player,w=p.weapons[p.slot],d=weaponDefs[w.id];w.ammo=d.mag;updateHUD()");src=src.replace("let type=r<.27?'ammo':r<.49?'armor':r<.67?'grenade':r<.84?'double':'rapid'","let type=r<.48?'armor':r<.74?'double':'rapid'");
  src=src.replace("power:{double:0,rapid:0},player:","power:{double:0,rapid:0},healDropChance:.05,player:");src=src.replace("regen:0},};","regen:0,healPower:40},};");src=src.replace("if(Math.random()<.04)dropHealing(e.x,e.y);else if(Math.random()<.19)dropPickup(e.x,e.y);","if(Math.random()<game.healDropChance)dropHealing(e.x,e.y);else if(Math.random()<.16)dropPickup(e.x,e.y);");src=src.replace("const amount=Math.min(40,p.maxHp-p.hp);p.hp=Math.min(p.maxHp,p.hp+40)","const amount=Math.min(p.healPower,p.maxHp-p.hp);p.hp=Math.min(p.maxHp,p.hp+p.healPower)");
  src=src.replace(/function chooseUpgrades\(\)\{.*?\}\nfunction endGame/s,`function chooseUpgrades(){const pool=[{t:'Stopping Power',d:'+20% weapon damage.',f:()=>game.player.damageMult*=1.2},{t:'Fleet Foot',d:'+12% movement speed.',f:()=>game.player.moveMult*=1.12},{t:'Fast Hands',d:'+16% fire rate.',f:()=>game.player.fireMult*=1.16},{t:'Juggernaut',d:'+25 max health and restore 25 health.',f:()=>{game.player.maxHp+=25;game.player.hp=Math.min(game.player.maxHp,game.player.hp+25)}},{t:'Armor Plate',d:'+30 max armor and restore 45 armor.',f:()=>{game.player.maxArmor+=30;game.player.armor=Math.min(game.player.maxArmor,game.player.armor+45)}},{t:'Field Medicine',d:'+10 percentage points to zombie healing-drop chance.',f:()=>game.healDropChance=Math.min(.55,game.healDropChance+.10)},{t:'Potent Aid',d:'Healing pickups restore +15 more health.',f:()=>game.player.healPower+=15},{t:'Emergency Care',d:'Immediately restore 45 health.',f:()=>game.player.hp=Math.min(game.player.maxHp,game.player.hp+45)}].sort(()=>Math.random()-.5).slice(0,3);const grid=$('upgradeGrid');grid.innerHTML='';pool.forEach(u=>{const d=document.createElement('div');d.className='upgrade';d.innerHTML=\`<h4>\${u.t}</h4><p>\${u.d}</p><button>SELECT</button>\`;d.querySelector('button').onclick=()=>{u.f();UI.between.classList.add('hidden');state='playing';document.body.classList.add('game-live');nextWave();updateHUD()};grid.appendChild(d)});state='between';document.body.classList.add('game-live');UI.between.classList.remove('hidden')}
function endGame`);
  src=src.replace("if(game.wave>=8)saved.unlock=Math.max(saved.unlock,8);if(game.wave>=15)saved.unlock=Math.max(saved.unlock,15);if(game.wave>=22)saved.unlock=Math.max(saved.unlock,22);if(game.wave>=30)saved.unlock=Math.max(saved.unlock,30);","if(game.wave>=8&&selectedMap<maps.length-1)saved.unlock=Math.max(saved.unlock,selectedMap+2);");src=src.replace("if(state!=='playing'||!game)return;","if((state!=='playing'&&state!=='between')||!game)return;");src=src.replace("if(touchMode){mouse.worldX=p.x+touchAim.x*500;mouse.worldY=p.y+touchAim.y*500} if(mouse.down)shoot();","if(touchMode){mouse.worldX=p.x+touchAim.x*500;mouse.worldY=p.y+touchAim.y*500} if(state==='playing'&&mouse.down)shoot();");
  (0,eval)(src+'\n//# sourceURL=game-core-pc.js');setTimeout(()=>window.DeadSectorPCUI?.mountScale(),0);
}).catch(err=>{console.error(err);document.body.innerHTML='<div style="padding:30px;color:white;font-family:system-ui">DEAD SECTOR failed to load: '+String(err.message||err)+'</div>'});
})();