export const RANGE_SCALE = 7;

export const weaponDefs = {
  pistol: {
    name: 'M9 Sidearm',
    damage: 25,
    rate: 0.31,
    mag: 12,
    reload: 1.08,
    spread: 0.075,
    pellets: 1,
    rangeRating: 70,
    range: 70 * RANGE_SCALE,
    sound: 'pistol',
    color: '#e9eef5',
    cost: 0,
  },
  pistol2: {
    name: 'VX-12 Blue Pistol',
    damage: 34,
    rate: 0.24,
    mag: 16,
    reload: 1.18,
    spread: 0.065,
    pellets: 1,
    rangeRating: 60,
    range: 60 * RANGE_SCALE,
    sound: 'bluePistol',
    color: '#55aaff',
    cost: 2500,
  },
  shotgun: {
    name: 'M12 Breacher',
    damage: 24,
    rate: 0.82,
    mag: 8,
    reload: 1.65,
    spread: 0.31,
    pellets: 7,
    rangeRating: 35,
    range: 35 * RANGE_SCALE,
    sound: 'shotgun',
    color: '#f2c14e',
    cost: 5000,
  },
  rifle: {
    name: 'AR-47',
    damage: 34,
    rate: 0.115,
    mag: 24,
    reload: 1.5,
    spread: 0.07,
    pellets: 1,
    rangeRating: 100,
    range: 100 * RANGE_SCALE,
    sound: 'ak',
    color: '#ff8f66',
    cost: 12000,
  },
};

export const WALKER_VARIANTS = [
  { name: 'dark', color: '#30462b', speedBonus: 0 },
  { name: 'forest', color: '#4e7138', speedBonus: 4 },
  { name: 'green', color: '#79a94d', speedBonus: 8 },
  { name: 'light', color: '#b0d978', speedBonus: 12 },
];
